name: Deploy Nest.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Build Nest.js project
        run: npm run build

      - name: Install sshpass (for password-based SSH)
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean Droplet
        if: success()
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          APP_DIR: /grantt-Back  # Carpeta donde se aloja la API Nest.js
        run: |
          # Copiar los archivos al servidor usando sshpass
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r dist/* $USER@$HOST:$APP_DIR

          # Instalar dependencias en el servidor y reiniciar la aplicación
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST "
            cd $APP_DIR &&
            npm ci --omit=dev &&
            pm2 restart grantt-back  # Reinicia la aplicación usando PM2
          "
