name: Deploy Nest.js App 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Build Nest.js project
        run: npm run build

      - name: Install sshpass (for password-based SSH)
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean Droplet
        if: success()
        env:
           HOST: ${{ secrets.HOST }}
           USER: ${{ secrets.USER }}
           SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
           APP_DIR: /grantt-Back
        run: |
            # Copiar los archivos al servidor usando sshpass
            sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r dist/* $USER@$HOST:$APP_DIR

            # Instalar dependencias en el servidor y reiniciar la aplicación
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST "
            set -e # Detiene el script si falla algún comando
            set -x # Muestra los comandos que se ejecutan para depurar
            export NVM_DIR=\"$HOME/.nvm\" &&
            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" &&
            cd $APP_DIR &&
      /root/.nvm/versions/node/v21.7.3/bin/npm ci --omit=dev &&
      pm2 restart grantt-back
    "

